name: CI - Script-specific Tests
 
on:
  push:
    branches:
      - DEV
  pull_request:
    branches:
      - DEV
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html
 
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
 
      - name: Run relevant unit tests and generate HTML report
        run: |
          tests_to_run=()
 
          echo "Changed files:"
          while IFS= read -r file; do
            file_unescaped=$(echo "$file" | sed 's/\\//g')
            echo "  $file_unescaped"
 
            if [[ "$file_unescaped" =~ ^Implementation\ \(Codes\)/.+/src/.+\.py$ ]]; then
              inst_dir=$(dirname "$(dirname "$file_unescaped")")
              script_name=$(basename "$file_unescaped" .py)
              test_file="$inst_dir/tests/test_${script_name}.py"
 
              if [ -f "$test_file" ]; then
                echo "✅ Found test for $file_unescaped -> $test_file"
                tests_to_run+=("$test_file")
              else
                echo "⚠️ No test found for $file_unescaped"
              fi
            fi
          done <<< "${{ steps.changed-files.outputs.all_changed_files }}"
 
          if [ ${#tests_to_run[@]} -eq 0 ]; then
            echo "No relevant tests found, skipping."
            exit 0
          fi
 
          # Run all matched tests and generate HTML report
          pytest "${tests_to_run[@]}" -v --disable-warnings --html=report.html --self-contained-html
 
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html
